### ISSUE TITLE
Clear navbar elements on logging out

### ISSUE THREAD

**Issue by veerreshr** [veerreshr/team-maker#9]
**Todo:**

- [ ] Hide navbar elements on logout( Something wrong with state update)

**Ways to reproduce Issue:**

- When ever a person logs out, the contents in navbar are still visible

**Screenshot :** 
![image](https://user-images.githubusercontent.com/59141533/127361863-d098090e-4643-4999-9c31-3f4820f324b8.png)

**More info:** State updates are not reflected to navbar, so making sure state is properly reflected to navbar fixes the issue.

**Comment by rd-code-23** [comment]
Hi, i might be able to help with this

**Comment by veerreshr** [comment]
@rd-code-23 that's awesome. Assigning it to you, in case you need some help feel free to ask.

**Comment by rd-code-23** [comment]
@veerreshr ok thanks , give me a week and hopefully I can fix it.

**Comment by rd-code-23** [comment]
@veerreshr 
I made a pull request. should be fixed now.
